List to do estructure
PedroH-Neves/list-to-do pull request #1
Opened 2022-11-04 07:03 UTC by PedroH-Neves

Here I created a To Do List

- Used backpack to setup project
- I used javascript to iterate trought an array to create the tasks
- Add new CSS styles

2022-11-04 07:43 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @PedroH-Neves  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Great work using the same font as Figma design ☑️ 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-04 07:43 UTC, Nyame-Wolf commented on src/style.css
> +
Kindly fix the css to match the minimalistic design in the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)
<img width="479" alt="Screenshot 2022-11-04 at 10 38 31" src="https://user-images.githubusercontent.com/48546992/199918947-a08b0507-815e-4492-84e8-0706e1650688.png">
Your current design is not a clone of these
<img width="851" alt="Screenshot 2022-11-04 at 10 40 59" src="https://user-images.githubusercontent.com/48546992/199919322-abd8c8fa-6652-4b08-9708-f5172e2e5edb.png">

2022-11-04 21:44 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @PedroH-Neves  I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- You did a great job your design looks nice Kindly make sure your design looks like the design provide by microverse as it was required by the previous reviewer [here](https://github.com/PedroH-Neves/list-to-do/pull/1#discussion_r1013705337)and no need to implement functionalities of add and remove at this step :+1: 

## Your design
![image](https://user-images.githubusercontent.com/95297251/200077465-fecbce10-0b12-4a8e-afce-b12dd578cfd7.png)

## design provides 

![image](https://user-images.githubusercontent.com/95297251/200079361-1e7d35d9-8ef2-427f-8f7f-4b702ced9f06.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```Screenshot from 2022-11-04 23-25-13

2022-11-04 23:16 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️
## Required Changes ♻️

- You did a great job your design looks nice Kindly make sure your design looks like the design provide by microverse as it was required by the previous reviewer [here](https://github.com/PedroH-Neves/list-to-do/pull/1#discussion_r1013705337)and no need to implement functionalities of add and remove at this step :+1: 

## Your design

![image](https://user-images.githubusercontent.com/95297251/200087990-8cfa93f2-3fde-4be5-aaa3-15306e3569c4.png)

## design provides 

![image](https://user-images.githubusercontent.com/95297251/200079361-1e7d35d9-8ef2-427f-8f7f-4b702ced9f06.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-05 04:20 UTC, roshan-bajgain approved these changes
Hi @PedroH-Neves, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-05 05:35 UTC, merged